- name: Install s3cmd
  ansible.builtin.package:
    name:
      - s3cmd
    state: present

- name: Configure s3cmd
  ansible.builtin.template:
    src: "templates/s3cfg.j2"
    dest: "~/.s3cfg"
    mode: "0600"

- name: Copy backup script
  ansible.builtin.copy:
    src: "files/backup.sh"
    dest: "/usr/local/bin/backup-{{ game_name }}.sh"
    mode: "0755"

- name: Copy systemd service for backup
  ansible.builtin.template:
    src: "templates/backup.service.j2"
    dest: /etc/systemd/system/backup-{{ game_name }}.service
    mode: "0644"
  notify:
    - Restart backup service for {{ game_name }}

- name: Copy systemd timer for backup
  ansible.builtin.template:
    src: "templates/backup.timer.j2"
    dest: /etc/systemd/system/backup-{{ game_name }}.timer
    mode: "0644"
  notify:
    - Restart backup timer for {{ game_name }}
