- name: SteamCmd
  hosts: all
  vars_files:
    - vars/main.yml
    # The custom.yml file is not included in the repository, you have to create it yourself
    - vars/custom.yml
  roles:
    - steamcmd
    - game_server
    - backup
